nonebot/nonebot2

nonebot/plugin.py, nonebot/rule.py
https://docs.python.org/3/library/typing.html#typing.Tuple
> To specify a variable-length tuple of homogeneous type, use literal ellipsis, e.g. Tuple[int, ...].
=> Fix command type

nonebot/__init__.py, nonebot/drivers/__init__.py, nonebot/drivers/fastapi.py, tests/bot.py
不再由 NoneBot 自行注册协议适配器
由用户在 `nonebot.run` 之前选择需要的协议适配进行注册
```python
import nonebot
from nonebot.adapters.cqhttp import Bot
nonebot.init()
driver = nonebot.get_driver()
driver.register_adapter("cqhttp", Bot)
```
=> Refactor: 更新内置 register_adapter 逻辑

nonebot/__init__.py, nonebot/adapters/__init__.py, nonebot/adapters/cqhttp/bot.py, nonebot/adapters/cqhttp/bot.pyi, nonebot/adapters/ding/bot.py, nonebot/message.py, nonebot/typing.py
pylance报错
```
Cannot access member "register_adapter" for type "NoReturn"
Member "register_adapter" is unknownPylance (reportGeneralTypeIssues)
```
mypy报错
```
Need type annotation for 'driver'mypy(error)
```
大概是NoReturn不能和其他联用
~是的没错我又在水PR~
=> 修复几个错误的类型声明

docs/.vuepress/public/plugins.json
=> Plugin: 风格化字符串管理

docs/.vuepress/public/plugins.json
cause nb-cli cannot auto load wordbank
=> Hotfix: error module name for plugin wordbank

docs/api/matcher.md, docs/guide/cqhttp-guide.md
Update: cqhttp-mirai / cqhttp-mirai-embedded has been renamed to Onebot-Mirai / Onebot-Kotlin by its author [yyuueexxiinngg](https://github.com/yyuueexxiinngg). Since the embedded branch was abandoned, both links here point to master branch of [onebot-kotlin](https://github.com/yyuueexxiinngg/onebot-kotlin).
=> [Doc] Update: CQHTTP implementations rename

packages/nonebot-adapter-mirai/nonebot/adapters/mirai/message.py
The incoming string will be defaulted to `MessageSegment.plain` type
=> Fix exception raised when constructing `MessageChain` from string

docs/api/adapters/README.md, docs_build/adapters/README.rst, nonebot/adapters/_base.py, nonebot/adapters/_formatter.py
- **TODO**:
<details>
<summary><strong>Demo</strong></summary>
- **Example code**:
- ```python
import random
from nonebot.adapters.mirai import MessageEvent, Bot, MessageChain
from nonebot.plugin import on_message
handler = on_message()
@handler.handle()
async def _(bot: Bot, event: MessageEvent, state: dict):
new_message = MessageChain.template(
'{prefix:->11}{message}{suffix:,}').format(
prefix='11character'[:random.randint(0, 11)],
message=event.message_chain,
suffix=2**32 - 1)
await bot.send(event, new_message, at_sender=True)
```
- **Execution result**:
- ![](https://user-images.githubusercontent.com/32300164/131020839-ace6db2c-bbf4-4db1-b399-9429970b742e.png)
</details>
=> Feature: `str.format` like message formatting support

docs/api/adapters/README.md, nonebot/adapters/_message.py, nonebot/adapters/_template.py, packages/nonebot-adapter-mirai/nonebot/adapters/mirai/message.py
demo code (with mirai adapter):
```python
from nonebot.adapters.mirai import MessageEvent, Bot, MessageChain, MessageSegment
from nonebot.plugin import on_message
handler = on_message()
@handler.handle()
async def _(bot: Bot, event: MessageEvent, state: dict):
await handler.send(MessageChain.template(
MessageSegment.plain('test {event.source}') + MessageSegment.face(233) +
MessageSegment.plain('test {event.message_chain}')).format(event=event),
at_sender=True)
```
=> Feature: support use `Message` object as message template

docs/api/adapters/README.md, nonebot/adapters/_message.py, nonebot/adapters/_template.py
Planned in https://github.com/nonebot/discussions/discussions/41
Demo code:
```python
from nonebot.adapters.mirai import MessageEvent, Bot, MessageChain
from nonebot.plugin import on_message
handler = on_message()
@handler.handle()
async def _(bot: Bot, event: MessageEvent, state: dict):
await handler.send(MessageChain.template('{msg:face}').format(
msg=event.message_chain.extract_plain_text()),
at_sender=True)
```
=> Feature: support use `MessageSegment` factory method as message template format spec

nonebot/permission.py
Now you can use `onebot:1234567890` in superusers to specify the OneBot Adapter。
Of course it 's compatible with old superusers. For example: `1234567890` means users with user_id `1294567890` in all Adapters.
=> :sparkles: Compatible with cross-platform superusers

README.md, website/static/adapters.json
Mirai-API-HTTP adapter will no longer be maintained by NoneBot officialy.
=> Remove mirai-api-http related info from readme

website/static/plugins.json
由于 OneBot v11 适配器自 v2.0.0b1 起提供了命令冷却支持，且该插件已无力继续维护，故将该插件从商店移除。
=> Plugin: 移除冷却事件插件

.github/workflows/publish-bot.yml
CI can be triggered when github action pushes a commit.
=> 👷checkout with PAT

website/static/plugins.json
变更插件“风格化字符串管理”原始仓库已归档，该插件目前已迁移至仓库 [echobot-dev/nonebot-plugin-strman](https://github.com/echobot-dev/nonebot-plugin-strman) ，更名后重新在 PyPI 中发布。原插件商店信息需要更新，故提交 pr 修改。
=> Plugin: 风格化字符串管理 商店信息更新

.github/ISSUE_TEMPLATE/config.yml
现在应该是 <https://v2.nonebot.dev/store> 。
<https://v2.nonebot.dev/store.html> 会提示 404。
=> Docs: 修改议题模板中的错误链接

website/docs/tutorial/deployment.md
在 [github action](https://github.com/Bubbleioa/ioa-bot/runs/5250225969) 上出错 
Error: Unable to resolve action `bobheadxi/deployments@v0.6`, unable to find version `v0.6`
最新版本为 v0.6.2
=> Docs: 修复 ci/cd action 中错误的版本号

website/docs/tutorial/choose-driver.md, website/versioned_docs/version-2.0.0-beta.2/tutorial/choose-driver.md
在 python 3.8 之后 , win平台默认使用 `ProactorEventLoop` , 而 uvicorn 在启动 `reload` 后会强制绑定默认事件循环为 `SelectorEventLoop` , 后者在 win 平台的可使用性不如前者 , 也会导致一些使用 asyncio 的包出错(如 playwright) 
以下是一些相关信息
[uvicorn#529](https://github.com/encode/uvicorn/issues/529)
[python doc](https://docs.python.org/zh-cn/3.10/library/asyncio-platforms.html#windows)
=> Docs: 添加对 `fastapi_reload` 在 Windows 平台额外影响的说明

nonebot/drivers/aiohttp.py, nonebot/drivers/fastapi.py, nonebot/drivers/httpx.py, nonebot/drivers/quart.py, nonebot/drivers/websockets.py, nonebot/internal/driver/model.py, tests/test_driver.py
=> Feat: 支持 WebSocket 连接同时获取 str 或 bytes

website/docs/advanced/scheduler.md
I checked [APScheduler Documentation](https://apscheduler.readthedocs.io/en/3.x/modules/schedulers/asyncio.html) and found that the classname should be `AsyncIOScheduler` instead of `AsyncScheduler`
=> Docs: 修复定时任务一节中的部分拼写错误

nonebot/internal/adapter/event.py, nonebot/internal/params.py, nonebot/utils.py, tests/plugins/param/param_bot.py, tests/plugins/param/param_event.py, tests/plugins/param/param_state.py, tests/test_param.py
=> Fix: 修复依赖注入 bot event 参数 union 校验失败

nonebot/log.py
Decoding error may be raised when escape sequences couldn't be handled correctly.
=> Feature: 日志记录自动检测终端是否支持彩色

nonebot/plugin/__init__.py, nonebot/plugin/manager.py, nonebot/plugin/plugin.py, tests/plugins/metadata.py, tests/test_plugin/test_load.py
=> Feature: 添加插件元信息定义

nonebot/internal/adapter/message.py, pyproject.toml, tests/test_adapters/test_message.py
当 dict 存在额外数据时会导致报错
```python
from pydantic import parse_obj_as
parse_obj_as(MessageSegment, {"type": "test", "extra": "something"})
```
=> Fix: 修复 MessageSegment 在有额外数据时报错

website/docs/advanced/permission.md
https://github.com/nonebot/nonebot2/blob/e2289c78b0161e6bc0f2d086eb9ca57789b7280f/nonebot/internal/permission.py#L50-L56
这里是要求至少传 `bot` 和 `event` 两个参数，但是文档的例子只传了 `event`，这里修改下
=> Docs: 修改 `权限控制` 一节中主动调用的错误

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/release-drafter.yml, .pre-commit-config.yaml, CONTRIBUTING.md, poetry.lock, pyproject.toml
```bash
nonemoji commit [-e EMOJI] [-m MESSAGE] [-- ...]
```
=> Docs: 添加 nonemoji 并更新开发指南

nonebot/internal/params.py, nonebot/params.py
```diff
- def handle(state: T_State = State()):
+ def handle(state: T_State):
```
=> Feature: 移除过时的 State 注入参数

nonebot/__init__.py, nonebot/config.py, nonebot/dependencies/__init__.py, nonebot/drivers/aiohttp.py, nonebot/drivers/httpx.py, nonebot/drivers/quart.py, nonebot/drivers/websockets.py, nonebot/exception.py, nonebot/internal/adapter/adapter.py, nonebot/internal/adapter/bot.py, nonebot/internal/adapter/template.py, nonebot/internal/driver/driver.py, nonebot/internal/driver/model.py, nonebot/internal/matcher.py, nonebot/internal/params.py, nonebot/internal/permission.py, nonebot/internal/rule.py, nonebot/log.py, nonebot/message.py, nonebot/permission.py, nonebot/plugin/__init__.py, nonebot/plugin/load.py, nonebot/plugin/manager.py, nonebot/plugin/on.py, nonebot/plugins/echo.py, nonebot/plugins/single_session.py, nonebot/rule.py, tests/.coveragerc, tests/test_init.py
related issue: #1134 @A-kirami 
Example:
```log
09-07 08:35:54 [SUCCESS] nonebot | NoneBot is initializing...
09-07 08:35:54 [INFO] nonebot | Current Env: prod
09-07 08:35:54 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'TRACE', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'prod'}
09-07 08:35:54 [DEBUG] nonebot | Succeeded to load adapter "Onebot V11"
09-07 08:35:54 [DEBUG] nonebot | Adapter "Onebot V11" already exists
09-07 08:35:54 [SUCCESS] nonebot | Succeeded to import "xxx_plugin"
09-07 08:35:54 [SUCCESS] nonebot | Succeeded to import "nonebot.plugins.echo"
09-07 08:35:54 …
```
=> Feature: 调整日志输出格式与等级

nonebot/__init__.py
> importlib.metadata 是一个提供对已安装包的元数据访问的库。这个库部分建立在 Python 的导入系统上，旨在取代 pkg_resources 的 [entry point API](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#entry-points) 和 [metadata API](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#metadata-api) 中的类似功能。 通过和 Python 3.7 或更高版本中的 [importlib.resources](https://docs.python.org/zh-cn/3.8/library/importlib.html#module-importlib.resources) 一同使用（对于旧版本的 Python 则作为 [importlib_resources](https://importlib-resources.readthedocs.io/en/latest/index.html) 向后移植），这可以消除对使用较旧且较为低效的 pkg_resources 包的需要。
移除对setuptools的依赖，移除变量`nonebot.VERSION`支持，自行使用`packaging.version.parse`
=> Feature: 使用 `importlib.metadata` 替换 `pkg_resources`

nonebot/internal/matcher.py, nonebot/message.py
=> Fix: 修复 run pre/post hook 没有在正确的上下文中运行

nonebot/internal/adapter/bot.py
=> Fix: Bot `__getattr__` 不再对 `__xxx__` 方法返回

website/docs/tutorial/configuration.md, website/versioned_docs/version-2.0.0rc2/tutorial/configuration.md
Command Start 和 Command Separator 代码块里面是大括号
=> Docs: 修正文档中部分配置文件示例的符号误用

website/docs/advanced/publish-plugin.md, website/versioned_docs/version-2.0.0rc2/advanced/publish-plugin.md
在 文档 `进阶`-> `发布插件` 中，有三处 `Nonebot商店` 指向 `/store.html`，分别位于:
- [申请发布到 NoneBot2 插件商店](https://v2.nonebot.dev/docs/advanced/publish-plugin#%E7%94%B3%E8%AF%B7%E5%8F%91%E5%B8%83%E5%88%B0-nonebot2-%E6%8F%92%E4%BB%B6%E5%95%86%E5%BA%97)
- [等待插件发布处理](https://v2.nonebot.dev/docs/advanced/publish-plugin#%E7%AD%89%E5%BE%85%E6%8F%92%E4%BB%B6%E5%8F%91%E5%B8%83%E5%A4%84%E7%90%86)
- [完成](https://v2.nonebot.dev/docs/advanced/publish-plugin#%E5%AE%8C%E6%88%90)  
其会导致部分用户从此页无法进入正确的商店页面，
而在 `开始` -> `安装第三方插件` 中，对商店的指向链接是正确的。
本请求将相关链接修改为了 `/store`，希望对贵项目有所帮助
以上
=> Docs: 修复文档中部分超链接跳转到 /store.html 的问题

.github/workflows/publish-bot.yml
在 Linux, Python 3.10 环境下测试插件加载情况。
并且可通过评论 `/skip` 跳过插件测试。
=> CI: 添加插件加载测试

nonebot/exception.py
exception 有自己的 `__str__` 方法，默认返回 args。如果要显示 NoneBotException 的 repr 需要覆盖该方法。
=> Fix: 修复异常在 traceback 中无法正常显示信息

website/static/plugins.json
最近又写了些东西，改了一下描述，以及删除了ayaka_who_is_suspect插件，原因是ayaka_games中已集合该插件
=> Plugin: 删除 ayaka_who_is_suspect 插件

nonebot/drivers/aiohttp.py, nonebot/drivers/fastapi.py, nonebot/drivers/httpx.py, nonebot/drivers/quart.py, nonebot/drivers/websockets.py
=> Feature: 在加载 driver 引发 ImportError 时，使用 `raise from e`

.github/workflows/publish-bot.yml
不再使用 main 标签，这样我就能在 main 开发，不再需要 dev 分支了。
=> CI: 发布机器人使用 latest 标签

website/versioned_docs/version-2.0.0rc3/start/installation.mdx
=> Docs: pip 安装指令添加引号

nonebot/internal/adapter/adapter.py
=> Fix: 修复适配器能断开非自身所有的 Bot 对象

nonebot/plugin/on.py, nonebot/plugin/plugin.py, tests/plugins/matcher/matcher_process.py, tests/plugins/plugin/matchers.py, tests/test_matcher/test_matcher.py, tests/test_plugin/test_on.py
=> Fix: 检测运行时创建响应器的插件

nonebot/drivers/_lifespan.py, nonebot/drivers/aiohttp.py, nonebot/drivers/fastapi.py, nonebot/drivers/httpx.py, nonebot/drivers/none.py, nonebot/drivers/quart.py, nonebot/drivers/websockets.py, tests/test_driver.py
lifespan 将**顺序**执行所有操作，不再并行。
`fastapi` deprecated `on_event`
=> Feature: 重构驱动器 lifespan 方法

.github/workflows/noneflow.yml, .github/workflows/publish-bot.yml
=> CI: 使用最新的 NoneFlow

nonebot/rule.py, tests/test_rule.py
=> Fix: shell command 包含富文本时报错信息出错

website/static/plugins.json
插件 nonebot-plugin-mcqq 与 nonebot-plugin-mcqq-mcrcon 已合并为 nonebot-plugin-mcqq
=> Plugin: 移除 `MC_QQ_MCRcon`

nonebot/drivers/none.py
暴露 exit 接口，方便serverless/云函数在处理完成后退出
=> Feature: 支持主动停止 `none` 系列驱动器

website/versioned_docs/version-2.0.0rc4/tutorial/handler.mdx
📝 Docs: 修复获取事件信息文档代码范例中缺失的 import (# 1982)
=> Docs: 修复事件处理函数文档代码范例中缺失的 import

website/versioned_docs/version-2.0.0rc4/tutorial/event-data.mdx
📝 Docs: 修复获取事件信息文档代码范例中的高亮行（# 1983）
=> Docs: 修复获取事件信息文档代码范例中的高亮行

website/docs/advanced/matcher.md
Add `nonebot-plugin-alconna` introduction in advance/matcher
=> Docs: 添加 Alconna 响应器介绍

website/docs/advanced/plugin-info.md
由于插件元数据部分文档未跟随 #1015 和 #2012 同步更新，本更改将更新插件元数据部分内容。
=> Docs: 更新插件元数据的相关描述

poetry.lock, pyproject.toml, tests/conftest.py, tests/fake_server.py, tests/plugins/matcher/matcher_permission.py, tests/test_adapters/test_message.py, tests/test_adapters/test_template.py, tests/test_driver.py, tests/test_init.py, tests/test_matcher/test_matcher.py, tests/test_param.py, tests/test_rule.py, tests/test_utils.py, tests/utils.py
- 使用本地 echo server 代替 httpbin
- 整理或添加了部分测试
=> Test: 移除 httpbin 并整理测试

website/docs/tutorial/message.md, website/versioned_docs/version-2.0.0/tutorial/message.md
我们还可以使用消息序列的 `only` 方法来检查消息中是否仅包含指定的消息段。
```python
message = Message(
[
MessageSegment.text("test"),
MessageSegment.text("test2"),
]
)
message.only("text") is True
message.only(MessageSegment.text("test")) is False
```
=> Docs: 补充 Message.only 文档

nonebot/drivers/aiohttp.py, nonebot/drivers/fastapi.py, nonebot/drivers/httpx.py, nonebot/drivers/none.py, nonebot/drivers/quart.py, nonebot/drivers/websockets.py, nonebot/typing.py, nonebot/utils.py
deprecate `nonebot.typing.overrides`. use `typing_extensions.override` instead.
=> Feature: 使用 `typing.override` 标记

nonebot/internal/driver/model.py, tests/test_driver.py
~`{name:FileContent} -> (name, (None, FileContent, None))`~
`{name:FileContent} -> (name, (name, FileContent, None))`
httpx驱动器上传失败 #1647 
nb model.py内会把`files={"test":b"test"}`处理成，`("test", (None, b"test", None))`
> httpx
当FileTypes为`bytes`，不是`Tuple[Optional[str], FileContent, Optional[str]]`时，httpx会默认`file_name="upload"`
但传的是 `Tuple[None, FileContent, Optional[str]]` ，httpx会处理成FileField -> `(None, b'test')`
( 这会导致server端收不到文件?
```python
if isinstance(value, tuple):
if len(value) == 2:
filename, fileobj = value  # type: ignore
elif len(value) == 3:
filename, fileobj, content_type = value  # type: ignore
else:
filename, fileobj, content_type, headers = value  # type: ignore
else:
filename = Path(str(getattr(value, "name", "upload"))).name
```
> aiohttp
没看(
test_file
```python
files=[ …
```
=> Fix: 设置 file request 默认 filename

nonebot/dependencies/__init__.py, nonebot/dependencies/utils.py, nonebot/internal/params.py, tests/plugins/param/param_depend.py, tests/test_param.py, website/docs/advanced/dependency.mdx
=> Feature: 支持子依赖定义 Pydantic 类型校验

nonebot/internal/params.py, tests/plugins/param/param_arg.py, tests/plugins/param/param_depend.py, tests/test_param.py
当前的 `Annotated` 子依赖支持优先使用 metadata 中的**第一个**子依赖。
此 PR 将行为更改成优先使用 metadata 中的**最后一个**子依赖。
借助嵌套 `Annotated` 会被展平，metadata 顺序由最内层向外的特性（`assert Annotated[Annotated[int, ValueRange(3, 10)], ctype("char")] == Annotated[int, ValueRange(3, 10), ctype("char")]`），可以实现 `Annotated` 子依赖的复用：
假设上游提供一个 `User` 子依赖 
```python
User = Annotated[_User, _get_user]
@handler.handle()
async def _(user: User):
...
```
在下游，可以重写 `User` 的依赖注入逻辑，而复用 `User` 的类型标注：
```python
CustomUser = Annotated[User, _custom_get_user()]
@handler.handle()
async def _(user: CustomUser):
...
```
参见：
- #1832
- https://docs.python.org/3/library/typing.html#typing.Annotated
=> Feature: 优先使用 `Annotated` 的最后一个子依赖

nonebot/internal/adapter/bot.py, tests/test_adapters/test_bot.py
=> Fix: bot.call_api 在被 called api hook mock 后应该忽略 exception

nonebot/rule.py, tests/test_rule.py
采用 [nonebot/adapter-telegram](https://github.com/nonebot/adapter-telegram) 作为 Telegram 的 adapter 时，带有命令的消息是分段的。例如 `"/weather Beijing"` 将会被分为 `["/weather", " Beijing"]` (注意第二段包含空白符)。
现有的命令 parsing 的结果是
- `prefix[CMD_ARG_KEY] = " Beijing"` (包含了空白符)
- `prefix[CMD_WHITESPACE_KEY] = None` (无法识别空白符)
在这种场景下，`on_command` 的 `force_whitespace` 参数也会失效。
增加对于分段消息的处理。修复后的 parsing 结果是
- `prefix[CMD_ARG_KEY] = "Beijing"` (删除了左侧空白符)
- `prefix[CMD_WHITESPACE_KEY] = " "`
=> Feature: 添加多消息段命令解析支持

nonebot/drivers/fastapi.py, nonebot/drivers/none.py, nonebot/drivers/quart.py, nonebot/internal/adapter/adapter.py, nonebot/internal/driver/_lifespan.py, nonebot/internal/driver/abstract.py, tests/test_driver.py
=> Fix: 新增 `Lifespan._on_ready()` 供适配器使用

nonebot/internal/adapter/template.py, tests/test_adapters/test_template.py
To prevent potential information leak caused by format string injection.
=> Fix: `MessageTemplate` 禁止访问私有属性

nonebot/params.py, tests/plugins/param/param_state.py, tests/test_param.py
[Match.group()](https://docs.python.org/zh-cn/3/library/re.html#re.Match.group) 无参数时返回整个正则表达式匹配的字符串, 也可以通过传入参数获得特定的捕获组.
而 `RegexStr()` 现在只支持无参数调用, 不支持传入参数.
此 pull request 实现了向 `RegexStr()` 传入参数以获得特定捕获组的功能.
例：
```python
matcher = on_regex(r"\[cq:(?P<type>.*?),(?P<arg>.*?)\]")
@matcher.handle()
async def _(type_: str = RegexStr(1), arg: str = RegexStr("arg")):
...
```
=> Feature: 带参数的 `RegexStr()`

nonebot/plugin/load.py, tests/plugins/metadata_3.py, tests/test_plugin/test_load.py
修复前:
插件A: `{"~qq", "~kook"}`
插件B: `{"nonebot.adapters.qq", "nonebot.adapters.kook"}`
结果为空
修复后
结果为 `{"nonebot.adapters.qq", "nonebot.adapters.kook"}`
=> Bug: inherit_supported_adapters 在展开缩写前取交集

README.md
=> Docs: 添加 Tailchat 适配器说明

assets/plugins.json
目前已经发现插件 `nonebot-plugin-covid` 和 `nonebot-plugin-molar-mass` 已在 PyPI 上删除无法访问，建议将其移出插件索引。
=> Plugin: 移除已在 PyPI 上删除的 `covid` 插件和 `molar-mass` 插件

website/docs/best-practice/testing/README.mdx, website/docs/best-practice/testing/behavior.mdx, website/versioned_docs/version-2.2.1/best-practice/testing/README.mdx, website/versioned_docs/version-2.2.1/best-practice/testing/behavior.mdx, website/versioned_docs/version-2.3.0/best-practice/testing/README.mdx, website/versioned_docs/version-2.3.0/best-practice/testing/behavior.mdx, website/versioned_docs/version-2.3.1/best-practice/testing/README.mdx, website/versioned_docs/version-2.3.1/best-practice/testing/behavior.mdx
修复使用 `console` 适配器的单元测试示例代码中的 `User` 参数
```python
class User:
"""用户"""
id: str
avatar: str = field(default="👤")
nickname: str = field(default="User")
```
相关 PR：https://github.com/nonebot/adapter-console/pull/34
=> Docs: 修复单元测试示例代码

website/docs/advanced/matcher.md, website/versioned_docs/version-2.2.1/advanced/matcher.md, website/versioned_docs/version-2.3.0/advanced/matcher.md, website/versioned_docs/version-2.3.1/advanced/matcher.md
I can't use it, I found the answer from #1152
=> Docs: `on_keyword` 参数类型错误

nonebot/internal/driver/combine.py, nonebot/typing.py, yarn.lock
=> Fix: 错误的类型标注和 annotated 处理

nonebot/compat.py, nonebot/dependencies/utils.py, tests/test_compat.py
缓存 pydantic 的 TypeAdapter 来避免高耗时的类型分析。
fix #2841 
performance before:
[result.json](https://github.com/user-attachments/files/16571813/result.json)
performance after:
[result_new.json](https://github.com/user-attachments/files/16571812/result_new.json)
<details><summary>Benchmark Code</summary>
<p>
benchmark code:
```python
from typing import Any
from nonebot.adapters import Bot, Event
from nonebot.dependencies import Dependent
from nonebot.internal.adapter.message import Message
from nonebot.params import Depends, BotParam, EventParam, DependParam
class FakeBot(Bot):
async def send(self, event: Event, message, **kwargs: Any) -> Any: ...
class FakeEvent(Event):
def get_type(self) -> str: ...
def get_event_name(self) -> str: ...
def get_event_description(self) -> str: ...
def …
```
=> Feature: 优化依赖注入在 pydantic v2 下的性能

website/docs/appendices/config.mdx, website/versioned_docs/version-2.3.0/appendices/config.mdx, website/versioned_docs/version-2.3.1/appendices/config.mdx, website/versioned_docs/version-2.3.2/appendices/config.mdx
Windows 系统中有两种命令行, 其中的 powershell 设置命令行的方式和 cmd 有所不同, 本 PR 更新了 powershell 中正确设置环境变量的方法
参考: https://learn.microsoft.com/zh-cn/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.4
=> Docs: 添加 Windows Powershell 设置环境变量方法

nonebot/drivers/websockets.py
=> Feature: 添加 websockets 驱动器 proxy 连接警告

assets/plugins.json
- 🗑️删除插件：`nonebot-plugin-ntqq_restart`
- ℹ️下架原因：
1. 不再维护
2. 因Windows依赖问题无法通过商店插件测试
3. 已转移至新项目[LLOneBot-Master](https://github.com/kanbereina/nonebot-plugin-llob-master)（nonebot-plugin-llob-master）
=> Plugin: 删除插件 `nonebot-plugin-ntqq-restart`

assets/plugins.json
🗑️删除插件：[nonebot-plugin-llob-master](https://github.com/kanbereina/nonebot-plugin-llob-master)
ℹ️下架原因：因学业精力有限，不再维护
=> Plugin: 删除插件 `nonebot-plugin-llob-master`

.github/workflows/website-preview-cd.yml, .github/workflows/website-preview-ci.yml
Related to: [GHSA-mjw5-7mvp-34wc](https://github.com/nonebot/nonebot2/security/advisories/GHSA-mjw5-7mvp-34wc)
=> Security: restrict workflow context

assets/plugins.json5
将 `assets/plugins.json5` 文件中的` project_link` 字段同步为 `pypi` 中的 `name` 字段。
删除不存在于 pypi 的插件 `nonebot-plugin-talk-with-chatgpt`
=> CI: 更新 assets/plugins.json5  文件里的 project_link 字段

envs/pydantic-v1/poetry.lock, envs/pydantic-v2/poetry.lock, nonebot/drivers/aiohttp.py, nonebot/drivers/httpx.py, poetry.lock, pyproject.toml
=> Fix: httpx proxy 与 aiohttp timeout 参数新版本修改

.github/workflows/noneflow.yml
现在使用的 json5 格式不再需要经过 pre-commit 格式化。
=> CI: 删除 NoneFlow 中关于 pre-commit 的部分

.github/ISSUE_TEMPLATE/adapter_publish.yml, .github/ISSUE_TEMPLATE/bot_publish.yml, .github/ISSUE_TEMPLATE/plugin_publish.yml
NoneFlow 当前还支持删除商店内容和修改插件配置，现在添加专门的发布标签方便进行判断。
=> Develop: 发布议题模板增加 Publish 标签

assets/plugins.json5
这个插件已经删除了全部on响应器,已经是一个普通模块了，不适合再当做插件用
=> Plugin: 删除插件 nonebot_plugin_clovers

README.md
=> Docs: 添加 黑盒语音 适配器描述

website/src/components/Store/Layout.tsx, website/src/components/Store/Toolbar.tsx, yarn.lock
当前移动端侧边栏存在问题，在切换路由时，会出现不可折叠的部分被折叠，无法手动重新展开。
例如：经由 navbar 从“开源之夏”跳转至“深入”，再跳转回“开源之夏”时展开侧栏，侧边栏中“开发者”一栏被折叠。
=> Docs: 修复移动端侧边栏折叠状态异常

.github/workflows/noneflow.yml
将测试结果上传至 artifact 中，这样合并之后或者解决冲突都不需要重新测试，直接下载 artifact 中的结果即可。
https://github.com/nonebot/noneflow/pull/408
=> CI: 适配 NoneFlow 4.4.0

nonebot/utils.py
fix: https://results.pre-commit.ci/run/github/289605524/1752142000.RtAoObUdRG2Q6oDFcs4uhg
=> Fix: `RUF005` tuple 拼接

nonebot/drivers/__init__.py, nonebot/drivers/aiohttp.py, nonebot/drivers/httpx.py, nonebot/drivers/websockets.py, nonebot/internal/driver/__init__.py, nonebot/internal/driver/abstract.py, nonebot/internal/driver/model.py, tests/test_driver.py
=> Feature: 细化内置驱动器请求参数中的超时控制颗粒度

.github/actions/setup-node/action.yml
This pull request updates the Node.js setup configuration in the GitHub Actions workflow to use the latest LTS version instead of a fixed version. This ensures that the project always runs on the most up-to-date, stable Node.js release.
* GitHub Actions: Changed the `node-version` in `.github/actions/setup-node/action.yml` from `"18"` to `lts/*` to automatically use the latest LTS Node.js version.
=> CI: 升级文档构建 node 版本
