.editorconfig
nonebot/adapters/cqhttp.py
nonebot/adapters/cqhttp.pyi
nonebot/message.py
tests/test_plugins/test_message.py
tests/test_plugins/test_package/test_command.py

update cqhttp apis. close #4

---

docs/api/log.md
nonebot/__init__.py
nonebot/adapters/__init__.py
nonebot/adapters/cqhttp.py
nonebot/config.py
nonebot/drivers/__init__.py
nonebot/drivers/fastapi.py
nonebot/log.py
nonebot/matcher.py
nonebot/message.py
nonebot/plugin.py
nonebot/plugins/base.py
nonebot/rule.py
poetry.lock
pyproject.toml
tests/bot.py
tests/test_plugins/test_package/test_command.py

更换nonebot内置logger为loguru，并提供logging intercept handler

Log: 使用loguru作为内置logger. Close #7

---

nonebot/drivers/fastapi.py
nonebot/rule.py

事件处理将在后台处理，防止阻塞
修复 command 为空时出现错误

Update: 事件处理后台执行

---

nonebot/__init__.py
nonebot/matcher.py
nonebot/permission.py
nonebot/plugin.py
nonebot/rule.py

Add Matcher Group and Command Alias/Group Support

---

docs/api/plugin.md
docs/api/rule.md
nonebot/plugin.py
nonebot/plugin.pyi
nonebot/rule.py

Issue33: 修改Command实现逻辑

---

nonebot/drivers/fastapi.py

修改Authorization头鉴权方式，支持Bearer以及Token

Issue35：修改鉴权限制

---

.github/ISSUE_TEMPLATE/plugin-publish.md

Fix: Plugin publish template

---

docs/api/typing.md
nonebot/message.py
nonebot/typing.py
poetry.lock

- before matcher run
- after matcher run
- after event handled

New: add pre and post processors (#40)

---

nonebot/__init__.py

使用 `pkg_resources` 获取 `Distribution` 的 `Metadata`
相关问题:
- #44

New: add __version__ for nonebot module

---

docs/.vuepress/public/plugins.json
docs/guide/creating-a-handler.md

Plugin: rauthman

---

nonebot/adapters/cqhttp/__init__.py

回复非机器人QQ未能移除紧随at QQ
相关：#65 #66

Fix: resolve reply message

---

nonebot/message.py

有时处理消息会用到rule的中间结果，想先全收进来再判断，这样就需要动态决定是否block

传递matcher抛出的StopPropagation

---

nonebot/message.py

Fix: running expired matcher

---

.github/workflows/plugin_issue.yml

试试看？感觉没问题。
如果出问题就直接禁用😂
<https://github.com/he0119/nonebot2-plugin-issue-bot>

ci: 添加插件议题机器人

---

.github/workflows/plugin_issue.yml

修复了这个问题 <https://github.com/he0119/nonebot2-plugin-issue-bot/issues/33>

:construction_worker: update plugin issue bot

---

docs/.vuepress/public/plugins.json

Plugin NoneBot离线文档

---

docs/.vuepress/public/plugins.json

Plugin: Sentry日志监控

---

.github/workflows/build_docs.yml
.github/workflows/upload_docs.yml

Fix: GHSL-2020-244

---

docs/.vuepress/public/plugins.json

Plugin: 前端测试机器人插件

---

docs/.vuepress/public/plugins.json

Plugin: 定时任务

---

docs/.vuepress/public/plugins.json

Plugin: 图片搜索

---

docs/.vuepress/public/plugins.json

Plugin: 通用数据库连接

---

docs/.vuepress/public/plugins.json

Plugin: translator

---

docs/api/matcher.md
docs/api/plugin.md
docs/api/typing.md
nonebot/matcher.py
nonebot/plugin.py
nonebot/plugin.pyi
nonebot/typing.py
tests/test_plugins/test_metaevent.py

创建一个state工厂函数，在run之前根据bot, event返回一个state以供运行使用

New: add state factory support

---

docs/api/drivers/README.md
docs/api/typing.md
nonebot/drivers/__init__.py
nonebot/drivers/fastapi.py
nonebot/typing.py
tests/test_plugins/test_ws_hook.py

Add `websocket connection hook` and `websocket disconnection hook`
resolve #118

New: WebSocket Connection Hook

---

nonebot/message.py

fix incorrect removing temp matcher

---

nonebot/adapters/cqhttp/bot.py

fix cqhttp message type guess

---

nonebot/adapters/cqhttp/bot.py

ensure message is not empty (fix #139)

Fix: empty message when using array post format

---

nonebot/drivers/fastapi.py

add fastapi driver configs

---

docs/.vuepress/public/plugins.json

Plugin: 模拟抽卡

---

docs/.vuepress/public/plugins.json

Plugin: nonebot-plugin-wordbank

---

docs/api/config.md
docs/api/plugin.md
docs/guide/basic-configuration.md
nonebot/__init__.py
nonebot/config.py
tests/.env

New: common config loading from .env

---

docs/.vuepress/public/plugins.json

Plugin: 冷却事件

---

docs/.vuepress/public/plugins.json

Plugin: mqtt接入

---

docs/.vuepress/public/plugins.json

Plugin: 消息交互式 python 解释器

---

docs/.vuepress/public/plugins.json

Plugin: songpicker2

---

docs/api/adapters/ding.md
docs/api/rule.md
nonebot/message.py
nonebot/rule.py

Fix rule override state

---

docs/api/plugin.md
nonebot/plugin.py
nonebot/plugin.pyi

Fix: `MatcherGroup` rule override

---

.github/workflows/build_docs.yml
docs/.vuepress/config.js
docs/api/README.md
docs/api/drivers/quart.md
docs_build/README.rst
docs_build/drivers/quart.rst
nonebot/drivers/quart.py
poetry.lock
pyproject.toml
tests/.env.dev

New: 添加一个使用Quart的Driver

---

nonebot/adapters/mirai/bot.py
nonebot/adapters/mirai/event/__init__.py
nonebot/adapters/mirai/event/message.py
nonebot/adapters/mirai/message.py
nonebot/adapters/mirai/utils.py
nonebot/matcher.py
nonebot/plugin.py
nonebot/rule.py
tests/test_plugins/test_mirai.py

~~又手滑, 傻逼Github非要绑定一个Enter到发布~~
Fixes #198 
貌似有对命令处理行为的breaking change

Bug: 修复在Mirai中命令匹配无效的Bug

---

docs/.vuepress/public/plugins.json

Plugin: Arcaea 查分器

---

docs/.vuepress/public/plugins.json

Plugin: hk-reporter

---

docs/.vuepress/public/plugins.json

Plugin: 网易云无损音乐下载

---

docs/.vuepress/public/plugins.json

Plugin: nonebot-plugin-cocdicer

---

docs/.vuepress/public/plugins.json

Plugin: 跑团记录记录器

---

docs/.vuepress/public/plugins.json

fix nonebot_plugin_cocdicer link error

---

nonebot/plugins/single_session.py
packages/nonebot-adapter-mirai/nonebot/adapters/mirai/message.py

Fix: fix single session bug

---

docs/.vuepress/public/plugins.json

Plugin: nonebot-plugin-r6s

---

docs/.vuepress/public/plugins.json

Plugin: 猜猜看

---

docs/.vuepress/public/plugins.json

Plugin: 例：缩写查询器

---

docs/api/adapters/README.md
docs/api/adapters/cqhttp.md
docs/api/adapters/ding.md
docs/api/adapters/mirai.md
nonebot/adapters/_base.py
nonebot/matcher.py

fix prompt type changed after format

Fix: prompt type error

---

docs/.vuepress/public/plugins.json
docs/api/nonebot.md

Plugin: biliav小程序转换器

---

.github/workflows/plugin_issue.yml

ci: 更新商店发布议题机器人

---

docs/.vuepress/public/plugins.json

Plugin: 插件管理器

---

docs/api/drivers/fastapi.md
packages/nonebot-adapter-mirai/nonebot/adapters/mirai/event/request.py

fix: #271 mah adapter 不能接受好友请求

Bug: 修复mah adapter无法接受好友请求

---

docs/.vuepress/public/bots.json

Bot: HarukaBot

---

docs/.vuepress/public/bots.json

Bot: Omega Miya

---

docs/.vuepress/components/Bot.vue
docs/.vuepress/public/plugins.json
tests/.env

Fix: store bot display error

---

docs/.vuepress/public/plugins.json

Plugin: bilibili视频、番剧解析

---

docs/api/adapters/README.md
docs/api/adapters/ding.md
docs/api/matcher.md
docs/api/plugin.md
nonebot/adapters/_base.py
nonebot/drivers/fastapi.py
packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/bot.py
packages/nonebot-adapter-ding/nonebot/adapters/ding/bot.py
packages/nonebot-adapter-ding/nonebot/adapters/ding/utils.py
packages/nonebot-adapter-mirai/nonebot/adapters/mirai/bot.py
packages/nonebot-adapter-mirai/nonebot/adapters/mirai/bot_ws.py
poetry.lock
pyproject.toml

修复了cqhttp post上报错误的权限检查
Breaking Change:
- `Bot.check_permission` `body` 参数: `Optional[dict]` -> `Optional[bytes]`

Fix: cqhttp post secret checking error

---

packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/event.py
packages/nonebot-adapter-ding/nonebot/adapters/ding/event.py

统一adapters中MessageEvent get_session_id方法返回的内容

---

docs/.vuepress/public/plugins.json

Plugin: 本地数据存储

---

packages/nonebot-adapter-mirai/nonebot/adapters/mirai/utils.py

Fix #296 
修复单独被@报错问题，以及使机器人可以判断出在消息任意位置的@信息

修复单独被@报错问题，以及使机器人可以判断出在消息任意位置的@信息

---

docs/api/adapters/README.md
docs/api/adapters/ding.md
nonebot/adapters/_base.py
nonebot/typing.py
packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/bot.py
packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/bot.pyi
packages/nonebot-adapter-ding/nonebot/adapters/ding/bot.py
packages/nonebot-adapter-mirai/nonebot/adapters/mirai/bot.py

New: add call_api hook

---

nonebot/message.py

当事件处理函数执行异常时返回捕获的异常实例, 写headless testing要用 (~~又有继续咕nonebug的理由了~~)
看起来貌似不算breaking
另外: 格式化什么的麻烦一下, 我直接从本地复制上来的

为`handle_event`函数添加异常返回

---

docs/.vuepress/public/plugins.json

Plugin: 待办事项提醒（闹钟）

---

nonebot/log.py
nonebot/plugin/manager.py

Fix: log module name error

---

docs/.vuepress/public/bots.json

Updated new repository url for Bot: Omega Miya

Bot: change repository url

---

docs/.vuepress/public/bots.json

Bot: Github Bot

---

docs/.vuepress/public/plugins.json

Plugin: nonebot_plugin_puppet

---

docs/.vuepress/public/adapters.json

Adapter: gocq

---

docs/.vuepress/public/plugins.json

Plugin: Minecraft 服务器状态查询

---

docs/.vuepress/public/plugins.json

Plugin: Nonebot2插件轻量帮助列表

---

docs/.vuepress/public/plugins.json

Plugin: nonebot_plugin_gamedraw

---

docs/.vuepress/public/plugins.json

Plugin: nonebot-plugin-alias

---

docs/guide/mirai-guide.md

更新 Mirai-API-HTTP 用户指南

---

docs/.vuepress/public/plugins.json

Plugin: Nonebot2 消息撤回插件

---

docs/.vuepress/public/bots.json

Bot: YanXiBot

---

docs/.vuepress/public/bots.json

Bot: 绪山真寻bot

---

docs/.vuepress/public/bots.json
docs/.vuepress/public/plugins.json
packages/nonebot-adapter-mirai/nonebot/adapters/mirai/event/request.py

修复Mirai加群通过时报错

---

docs/.vuepress/public/plugins.json

Plugin: nonebot_plugin_pixivrank_search

---

docs/.vuepress/public/plugins.json

Plugin: nonebot_plugin_russian

---

docs/.vuepress/public/plugins.json

Plugin: nonebot_plugin_statistical

---

packages/nonebot-adapter-mirai/nonebot/adapters/mirai/bot.py

修复mirai adapter中上传相关api操作报错

---

docs/.vuepress/public/plugins.json

Plugin: nonebot_plugin_setu

---

docs/.vuepress/public/plugins.json

Plugin: nonebot_plugin_fr24

---

docs/.vuepress/public/bots.json

Bot: dumbot傻瓜机器人

---

docs/.vuepress/public/plugins.json

web-monitor will replace simdraw

Publish plugin web-monitor

---

docs/.vuepress/public/adapters.json

Adapter: feishu

---

docs/.vuepress/public/bots.json

Bot: DicePP

---

docs/.vuepress/public/plugins.json

Plugin: 和风天气

---

docs/.vuepress/public/plugins.json

Plugin: nonebot-plugin-autohelp

---

docs/.vuepress/public/plugins.json

Plugin: 孤寡机器人

---

docs/.vuepress/public/plugins.json

Plugin: 布谷机器人

---

docs/.vuepress/public/plugins.json

Plugin: nonebot-plugin-flexperm

---

packages/nonebot-adapter-mirai/nonebot/adapters/mirai/bot.py

Bugfix: remove mirai session expiry

---

docs/guide/mirai-guide.md
packages/nonebot-adapter-mirai/nonebot/adapters/mirai/bot.py

feature: mirai multiple accounts support

---

docs/.vuepress/public/plugins.json

Plugin: Epic 限免游戏资讯

---

docs/.vuepress/public/plugins.json

Plugin: ELF_RSS

---

docs/.vuepress/public/bots.json

Bot: SetuBot

---

docs/.vuepress/public/plugins.json

Plugin: ATRI语音包

---

nonebot/matcher.py
packages/nonebot-adapter-ding/nonebot/adapters/ding/bot.py
packages/nonebot-adapter-ding/nonebot/adapters/ding/message.py

1. cannot send complicate message, such as actionCard
2. fix judge current connection mode

🐛 fix ding adapter issues

---

.github/workflows/publish_bot.yml

👷 update store publish bot

---

docs/.vuepress/public/plugins.json

Plugin: HanayoriBot

---

docs/.vuepress/public/plugins.json

Plugin: HTTP静态文件托管

---

docs/.vuepress/public/plugins.json

Plugin: SimpleMusic

---

nonebot/message.py

Fix: remove return value in event handle

---

docs/.vuepress/public/plugins.json

Plugin: pornhub风格图标生成

---

docs/api/adapters/README.md
nonebot/adapters/_message.py
nonebot/adapters/_template.py
pages/changelog.md

`MessageTemplate` now can format simple string and return string by default

Feature: template support raw string

---

docs/.vuepress/public/plugins.json

Plugin: leetcode提醒机器人

---

docs/.vuepress/public/plugins.json

Plugin: 另一个图片搜索

---

docs/.vuepress/public/plugins.json

Plugin: IT咨讯

---

docs/.vuepress/public/plugins.json

Plugin: lolheroes

---

docs/.vuepress/public/plugins.json

Plugin: nonebot_plugin_youthstudy

---

docs/.vuepress/public/plugins.json

Plugin: gocqapi

---

docs/.vuepress/public/plugins.json

Plugin: 工作性价比计算器

---

docs/.vuepress/public/plugins.json

Plugin: 诺基亚手机图生成

---

docs/.vuepress/public/plugins.json

Plugin: nonebot-plugin-asoulcnki

---

docs/.vuepress/public/plugins.json

Plugin: nonebot-plugin-petpet

---

docs/.vuepress/public/plugins.json

Plugin: ShindanMaker

---

docs/.vuepress/public/plugins.json

Plugin: 虚拟朋友

---

docs/.vuepress/public/plugins.json

Plugin: 在线运行代码

---

nonebot/drivers/fastapi.py

Fix: http2 for fastapi driver

---

docs/.vuepress/public/plugins.json

Plugin: 随机黑丝

---

docs/.vuepress/public/plugins.json

Plugin: picsbank

---

docs/.vuepress/public/plugins.json

Plugin: 剧集更新列表

---

docs/.vuepress/public/plugins.json

Plugin: lol比赛信息

---

docs/.vuepress/public/bots.json

Bot: SeaBot_QQ

---

docs/.vuepress/public/plugins.json

Plugin: OlivOS.nb2

---

docs/.vuepress/public/plugins.json

Plugin: 通过浏览器来生成图片

---

docs/.vuepress/public/plugins.json

Plugin: 简易群管

---

docs/.vuepress/public/plugins.json

Plugin: nonebot-plugin-logo

---

docs/.vuepress/public/plugins.json

Plugin: Memes generator

---

nonebot/adapters/_template.py
tests/adapters/test_template.py
tests/utils.py

Support user-defined format spec for message template

---

.github/workflows/publish-bot.yml

:construction_worker: update publish bot config

---

website/static/plugins.json

Plugin 群聊复读机

---

website/static/plugins.json

Plugin 插件管理器

---

website/static/plugins.json

Plugin 群文件直链提取器

---

website/static/plugins.json

Plugin: 转发姬

---

website/static/adapters.json

Adapter: 开黑啦

---

nonebot/matcher.py

Fix: fix matcher receive and arg detect

---

nonebot/plugin/manager.py
nonebot/plugin/plugin.py
tests/test_init.py

Fix: plugin load fail process

---

website/static/plugins.json

Plugin: 扔骰子

---

website/static/plugins.json

Plugin: 疯狂星期四

---

website/static/plugins.json

Plugin: 新冠疫情查询😷

---

website/static/plugins.json

Plugin: 人生重开模拟器

---

website/static/plugins.json

Plugin: 彩云小梦AI续写

---

nonebot/plugins/single_session.py
tests/test_single_session.py
tests/utils.py

Fix: single_session potential bug

---

website/static/plugins.json

Plugin: 天气查询

---

website/static/adapters.json

Adapter: mirai2

---

website/static/plugins.json

Plugin: nonebot_plugin_fortune

---

website/static/plugins.json

Plugin: 塔罗牌

---

website/static/plugins.json

Plugin: emoji 合成器

---

website/static/plugins.json

Plugin: 今天吃什么

---

website/static/plugins.json

Plugin: NoneBot 数据存储

---

website/static/plugins.json

Plugin: NoneBot的go-cqhttp启动器

---

website/static/plugins.json

Plugin: nonebot-general-rss

---

nonebot/plugin/load.py
nonebot/plugin/manager.py
tests/test_init.py
tests/test_plugin/test_load.py

Fix: require load plugin error

---

website/static/plugins.json

Plugin: go-cqhttp 频道支持适配补丁

---

website/static/plugins.json

Plugin: 棋类游戏

---

website/static/plugins.json

Plugin: 词云

---

website/static/plugins.json

Plugin: FG(Fifth Generation)

---

nonebot/adapters/_message.py
tests/test_adapters/test_message.py
tests/test_adapters/test_template.py

Remove mapping construct for class `Message` and improve typing for `Message` and `MessageSegment`

Fix: rewrite message typing and construct

---

website/static/plugins.json

Plugin: 聊天记录插件

---

website/static/plugins.json

Plugin: nonebot-plugin-setu2

---

website/static/plugins.json

Plugin: random-cat

---

website/static/plugins.json

Plugin: 群聊反闪照

---

website/static/plugins.json

Plugin: random_cat_gif

---

website/static/plugins.json

Plugin: 无数据库的问答插件

---

website/static/plugins.json

Plugin: Fgo从者推理

---

nonebot/internal/adapter/template.py
tests/test_adapters/test_template.py
tests/utils.py

Fix `Message.template` format spec does not support static method

---

website/static/plugins.json

修改商店 `nonebot-plugin-strman` 插件的 `module_name` 错误名称。

Plugin: 修改 nonebot-plugin-strman 错误的 module_name

---

website/static/plugins.json

Plugin: 轻量文字转图片插件

---

nonebot/internal/adapter/template.py
tests/test_adapters/test_template.py
tests/test_examples/test_weather.py
tests/utils.py

Bugfix: Potential message body injection vulnerability in `MessageTemplate`

---

website/static/bots.json

Bot: 琪露诺Bot

---

website/static/plugins.json

Plugin: おはよう！

---

website/static/plugins.json

Plugin: pixiv.net p站查询图片

---

website/static/plugins.json

Plugin: 60s读世界小插件

---

website/src/pages/changelog.md

Docs: 减小更新日志 toc 最大显示等级

---

.github/workflows/website-preview.yml

CI: 分离 pr 预览 action

---

.github/dependabot.yml

CI: 添加 dependabot 配置文件

---

website/static/plugins.json

Plugin: YetAnotherPicSearch

---

website/static/plugins.json

Plugin: 原神抽卡记录分析

---

website/static/plugins.json

Plugin: 每日一句

---

website/static/plugins.json

Plugin: update nonebot-bison

---

website/static/plugins.json

相关功能已合并至 [ELF_RSS](https://github.com/Quan666/ELF_RSS)

:fire: Plugin: 移除 nonebot-general-rss

---

website/static/plugins.json

Plugin: QQ自动续火花

---

website/static/plugins.json

Plugin: mockingbird

---

website/static/plugins.json

Plugin: 二维码识别与发送

---

website/static/plugins.json

Plugin: 游戏王卡查

---

website/static/plugins.json

:beers: Plugin: 动漫新闻

---

website/static/plugins.json

Plugin: 订阅推送管理

---

website/static/plugins.json

Plugin: bilibili通知插件

---

website/static/plugins.json

Plugin: 色图生成

---

website/static/plugins.json

Plugin: 21点游戏插件

---

website/static/plugins.json

Plugin: QQ自动同意好友申请

---

website/static/plugins.json

Plugin: Arcaea查分插件

---

website/static/plugins.json

Plugin: 成分姬

---

website/static/plugins.json

原 SimpleMusic 插件作者删库跑路了，希望替代原来的插件

Docs: 替换和移除部分已经失效的插件

---

website/static/plugins.json

Plugin: 第二个leetcode查询插件

---

website/static/plugins.json

Plugin: HikariSearch

---

website/static/plugins.json

Plugin: MediaWiki查询

---

website/static/plugins.json

Plugin: wordle猜单词

---

website/static/plugins.json

Plugin: 快速搜索

---

.github/workflows/publish-bot.yml

CI: 修复发布机器人的意外错误

---

website/static/plugins.json

Plugin: 语句抽象化

---

website/static/plugins.json

Plugin: 多适配器帮助函数

---

website/static/plugins.json

Plugin: 汉兜 Handle

---

website/static/plugins.json

Plugin: 扫雷游戏

---

website/static/plugins.json

[nonebot-plugin-test](https://github.com/nonebot/plugin-test) @yanyongyu
[nonebot-plugin-web](https://github.com/abrahum/nonebot_plugin_web) @abrahum
[nonebot-plugin-ipypreter](https://github.com/iyume/nonebot-plugin-ipypreter) @iyume
[nonebot-plugin-arcaea](https://github.com/iyume/nonebot-plugin-arcaea) @iyume
[nonebot-plugin-statistical](https://github.com/HibiKier/nonebot_plugin_statistical) @HibiKier
[nonebot-plugin-workscore](https://github.com/yzyyz1387/nonebot_plugin_workscore) @yzyyz1387
[nonebot-plugin-nokia](https://github.com/kexue-z/nonebot-plugin-nokia) @kexue-z
[nonebot-plugin-pctrl](https://github.com/CherryGS/nonebot_plugin_PCtrl) @CherryGS
[nonebot-plugin-wordbank](https://github.com/Joenothing-lst/word-bank) @Joenothing-lst …

Docs: 移除商店中的过期插件

---

website/static/plugins.json

Plugin: nonebot_plugin_draw

---

website/static/plugins.json

Plugin: splatoon2新闻

---

website/static/plugins.json

Plugin: 随机唐可可

---

website/static/plugins.json

Plugin: nonebot-plugin-dida

---

website/docs/tutorial/deployment.md

Docs: 更新 GitHub Action 部署文档

---

website/static/plugins.json

Plugin: 支付宝到账语音

---

website/static/plugins.json

Plugin: 答案之书

---

website/static/plugins.json

Plugin: 一言

---

website/static/plugins.json

Plugin: B站视频封面提取

---

nonebot/internal/adapter/template.py
tests/test_adapters/test_template.py

Fix: 修复`MessageTemplate`在没有格式化说明符时行为不正确的问题

---

website/static/plugins.json

Plugin: 中国象棋

---

website/static/plugins.json

Plugin: NoneBot2 文档搜索

---

website/static/bots.json

Bot: Inkar Suki

---

website/static/plugins.json

Plugin: 国际象棋

---

website/static/bots.json

Bot: ShigureBot

---

website/static/plugins.json

Plugin: 合成字符画(GIF)

---

website/static/plugins.json

Plugin: 幻影坦克图片合成

---

website/static/plugins.json

Plugin: 国内新冠疫情数据查询

---

website/static/plugins.json

Plugin: 语录娱乐

---

website/static/plugins.json

Plugin: 走迷宫

---

website/static/plugins.json

Plugin: 摸鱼日历

---

website/static/bots.json

Bot: 屑岛风Bot

---

website/static/plugins.json

Plugin: imageutils

---

nonebot/plugin/export.py
nonebot/plugin/load.py

Fix: 添加 export 方法 Deprecation 警告

---

website/static/plugins.json

Plugin: MockingBird语音

---

website/static/plugins.json

Plugin: 百度翻译

---

website/static/plugins.json

Plugin: 数据库连接插件

---

website/static/bots.json

Bot: LiteyukiBot-轻雪机器人

---

website/static/plugins.json

Plugin: 签到插件

---

website/static/plugins.json

Plugin: TETRIS Stats

---

website/static/plugins.json

Plugin: B站视频伪分享卡片

---

website/static/plugins.json

Plugin: 明日方舟工具箱

---

website/static/plugins.json

Plugin: imagetools

---

website/static/plugins.json

Plugin: Warframe时间查询

---

website/static/plugins.json

Plugin: Hikari-战舰世界水表查询

---

website/static/plugins.json

Plugin: 谁艾特我了

---

website/static/plugins.json

Plugin: 疫情小助手

---

website/static/plugins.json

Plugin: 青年大学习自动提交

---

website/static/plugins.json

Plugin: 命令重启机器人

---

website/static/bots.json

Bot: nya_bot

---

website/static/plugins.json

Plugin: nonebot_plugin_setu4

---

website/static/plugins.json

Plugin: smart_reply

---

website/static/plugins.json

Plugin: 历史上的今天

---

website/static/plugins.json

Plugin: BitTorrent

---

website/static/plugins.json

Plugin: 黑白名单

---

website/static/plugins.json

Plugin: nonebot-plugin-bread

---

website/static/plugins.json

Plugin: PicMenu

---

website/static/plugins.json

Plugin: 赛马

---

website/static/plugins.json

Plugin: 米游币商品自动兑换

---

website/static/plugins.json

Plugin: 一起燚xN吧

---

website/static/plugins.json

Plugin: 战地1、5战绩查询工具

---

website/static/plugins.json

Plugin: OSU查分插件

---

website/static/plugins.json

Plugin: ACC计算工具

---

website/static/plugins.json

Plugin: 自动回复（文i）插件

---

website/static/plugins.json

Plugin: b站视频每日推送

---

website/static/plugins.json

Plugin: 明日方舟寻访记录分析

---

website/static/plugins.json

Plugin: 处理好友添加和群邀请

---

website/static/bots.json

Bot: 真宵Bot

---

website/static/bots.json

Bot: changed my bot link in store.

---

website/static/plugins.json

Plugin: 群昵称时间

---

website/static/plugins.json

Plugin: 易命令

---

website/static/bots.json

Bot: SkadiBot

---

website/static/plugins.json

Plugin: 推送钩子

---

website/static/plugins.json

Plugin: 「能不能好好说话？」缩写翻译

---

nonebot/plugin/__init__.py
nonebot/plugin/export.py
nonebot/plugin/manager.py
nonebot/plugin/on.py
tests/plugins/nested/__init__.py
tests/plugins/nested/plugins/nested_subplugin.py
tests/plugins/nested/plugins/nested_subplugin2.py
tests/test_plugin/test_load.py

Fix: 修复插件父子关系识别错漏

---

website/static/plugins.json

Plugin: BAWiki

---

website/static/plugins.json

Plugin: MC_QQ通信

---

website/static/plugins.json

Plugin: 疫情小助手-频道版

---

website/static/plugins.json

Plugin: bangumi搜索

---

website/static/plugins.json

Plugin: wiki条目搜索、获取简介

---

website/static/plugins.json

Plugin: 简易群管（带入群欢迎）

---

website/static/plugins.json

Plugin: 小游戏合集

---

website/static/plugins.json

Plugin: 修改 QQ 续火花插件信息

---

website/static/plugins.json

Plugin: nonebot-plugin-drawer

---

website/static/plugins.json

Plugin: 每日人品

---

website/static/plugins.json

Plugin: 日韩中 VITS 模型原神拟声

---

nonebot/internal/adapter/message.py
tests/test_adapters/test_template.py

Fixes https://github.com/mnixry/nonebot-plugin-gocqhttp/issues/281

Fix: 修复当消息与不支持的类型相加时抛出的异常类型错误

---

website/static/plugins.json

Plugin: PixivBot

---

website/static/plugins.json

Plugin: 娶群友

---

website/static/plugins.json

Plugin: 工作性价比

---

website/static/plugins.json

Plugin: NoneBot 树形帮助插件

---

website/static/plugins.json

Plugin: 业余无线电助手

---

website/static/plugins.json

Plugin: 课表查询

---

nonebot/params.py
nonebot/rule.py
tests/test_rule.py
website/docs/tutorial/plugin/create-handler.md

Feature: shell command 添加富文本支持

---

website/static/plugins.json

Plugin: 话痨排行榜

---

website/static/plugins.json

Plugin: 面麻小助手

---

website/static/plugins.json

Plugin: MagiaDice骰娘及TRPGLOG

---

website/static/plugins.json

Plugin: 反馈及通知

---

website/static/plugins.json

Plugin: 雨课堂自动签到

---

website/static/plugins.json

Plugin: 自识别todo

---

website/static/plugins.json

Plugin: 不背单词

---

nonebot/plugin/load.py
nonebot/plugin/manager.py
nonebot/utils.py
tests/test_plugin/test_load.py

```python
nonebot.load_plugin("plugins.wtf")
nonebot.load_plugin("plugins.wtf")
nonebot.load_plugin(Path("plugins") / "wtf")
```

Featue: `load_plugin` 支持 `pathlib.Path`

---

website/static/plugins.json

Plugin: 赛博浅草寺

---

website/static/plugins.json

Plugin: 修仙模拟器

---

website/static/plugins.json

Plugin: 原神角色展柜查询

---

website/static/plugins.json

Plugin: MC_QQ_MCRcon

---

README.md
website/static/adapters.json

Adapter: Console

---

website/static/plugins.json

Plugin: 原神每日材料查询

---

website/static/plugins.json

Plugin: 米游社辅助工具

---

website/static/plugins.json

Plugin: 星际战甲事件查询

---

website/static/bots.json

Bot: 小白机器人

---

website/static/bots.json

Bot: GenshinUID

---

website/static/plugins.json

Plugin: 查询ETH合并日期

---

website/static/plugins.json

Plugin: Minecraft Server 聊天同步

---

website/static/plugins.json

Plugin: 图像超分辨率重建

---

website/static/plugins.json

Plugin: ayaka - 文字游戏开发辅助插件

---

website/static/plugins.json

Plugin: 狼人杀插件

---

website/static/bots.json

Bot: LittlePaimon

---

website/static/plugins.json

Plugin: nonebot物联网插件

---

website/static/bots.json

Bot: IdhagnBot

---

website/static/plugins.json

Plugin: BWIKI助手移植版

---

website/static/plugins.json

Plugin: 漂流瓶

---

website/static/plugins.json

Plugin: gal角色语音生成

---

website/static/plugins.json

Plugin: 阿里云盘福利码自动兑换

---

website/static/plugins.json

Plugin: PicStatus

---

website/static/plugins.json

Plugin: 图灵机器人

---

website/static/plugins.json

Plugin: 在线编曲

---

website/static/plugins.json

Plugin: 文字识别

---

website/static/plugins.json

Plugin: 监听者

---

website/static/plugins.json

Plugin: BiliRequestAll

---

website/static/plugins.json

Plugin: 真白萌自动签到

---

website/static/plugins.json

Plugin: 轮盘禁言小游戏

---

website/static/bots.json

As the title says. I modified my bot's labels and decription. Please merge if there's no mistake. Thanks a lot.

Bot: 修改 Inkar Suki 描述

---

website/static/adapters.json

Adapter: Ntchat

---

website/static/plugins.json

Plugin: 监测群事件

---

website/static/plugins.json

Plugin: 游戏王小程序查价

---

website/static/plugins.json

Plugin: novelai

---

website/static/plugins.json

Plugin: AI绘图

---

website/static/plugins.json

Plugin: bnhhsh -「不能好好说话！」

---

website/static/plugins.json

Plugin: ayaka衍生插件 - 小游戏合集

---

website/static/plugins.json

Plugin: ayaka衍生插件 - 谁是卧底

---

website/static/plugins.json

Plugin: ayaka衍生插件 - 时区助手

---

website/static/plugins.json

由于插件开发添加了很多新的功能，原有描述不够准确。对插件信息进行调整

Plugin: 补充 novelai 插件信息

---

website/static/plugins.json

Plugin: ayaka衍生插件 - 坏词撤回

---

website/static/plugins.json

Plugin: 二次元图像鉴赏

---

website/static/plugins.json

Plugin: 通用抽图/语音

---

website/static/plugins.json

Plugin: 更新 ayaka 插件的主页链接

---

website/static/plugins.json

Plugin: NoneBot SQLAlchemy封装

---

website/static/plugins.json

Plugin: 用户&群聊黑名单

---

website/static/plugins.json

Plugin: 反嘴臭插件

---

website/static/plugins.json

Plugin: 文本生成器

---

website/static/plugins.json

Plugin: 日麻寄分器

---

website/static/plugins.json

Plugin: 二次元化图像

---

website/static/bots.json

Bot: hsbot

---

website/static/plugins.json

Plugin: 日麻小工具

---

website/static/plugins.json

Plugin: 动漫资源获取

---

website/static/plugins.json

Plugin: 随个人

---

website/static/plugins.json

仅调整了sena之前发布过的插件的对应地址，以及标准了一下tag格式

Plugin: 由于Sena-nana项目拆分，之前的插件地址更改

---

website/static/bots.json

Bot: Bread Dog Bot

---

website/static/plugins.json

Plugin: Apex API Query

---

website/static/plugins.json

Plugin: 投胎模拟器

---

website/static/plugins.json

Plugin: b站用户直播号、粉丝、舰团数查询

---

website/static/plugins.json

Plugin: Colab-NovelAI

---

website/static/plugins.json

Plugin: sky光遇

---

website/static/plugins.json

Plugin: 免费版NovelAI生图插件

---

website/static/plugins.json

Plugin: 谁在窥屏

---

website/static/plugins.json

Plugin: 原神前瞻直播兑换码查询

---

website/static/plugins.json

Plugin: 记事本

---

nonebot/rule.py
tests/test_rule.py

Fix: 修复 ArgumentParser 错误信息叠加问题

---

website/static/plugins.json

Plugin: b站图片下载

---

website/static/plugins.json

Plugin: 动画截图追溯来源

---

website/static/plugins.json

Plugin: 免费快捷点歌插件

---

website/static/plugins.json

Plugin: ChatGPT

---

website/static/plugins.json

Plugin: 雀魂信息查询

---

website/static/plugins.json

Plugin: 图片背景消除

---

website/static/plugins.json

Plugin: 全群广播

---

website/static/plugins.json

Plugin: 汇率换算

---

website/static/plugins.json

Plugin: 权限控制

---

website/static/plugins.json

Plugin: multi-ChatGPT

---

website/static/plugins.json

Plugin: 随机配色方案

---

website/static/plugins.json

Plugin: 戒色打卡日记

---

website/static/plugins.json

Plugin: QQ群文件备份

---

website/static/plugins.json

Plugin: 熊老板

---

website/static/plugins.json

Plugin: GPT3

---

website/static/plugins.json

Plugin: 只因进化录

---

website/static/plugins.json

Plugin: 随机禁言

---

website/static/plugins.json

Plugin: 防撤回

---

tests/test_driver.py

Fix: 修复客户端请求未处理 cookies

---

website/static/plugins.json

Plugin: JAVA MC服务器信息查询

---

website/static/plugins.json

Plugin: 不要复读

---

website/static/plugins.json

Plugin: 战地群聊天插件

---

website/static/plugins.json

Plugin: 群友召唤术

---

website/static/plugins.json

Plugin: Ping

---

website/static/bots.json

Bot: RanBot

---

website/static/plugins.json

Plugin: 移除 `nonebot-plugin-filehost`

---

website/static/plugins.json

Plugin: 腾讯云图像变换

---

website/static/plugins.json

Plugin: 服务状态查询

---

website/static/plugins.json

Plugin: AnimalVoice_Convert

---

website/static/plugins.json

Plugin: 命令探查

---

nonebot/__init__.py

Feature: 添加 `logger` 重导出

---

website/static/plugins.json

Plugin: HttpCat🐱猫猫http状态码

---

website/static/plugins.json

Plugin: 主动消息撤回

---

.github/workflows/codecov.yml
.github/workflows/publish-bot.yml

仅在特定目录内文件修改后运行测试。
发布机器人减少不必要的运行 <https://github.com/nonebot/nonebot2-publish-bot/pull/99>。

CI: 优化触发条件减少无效运行

---

website/static/plugins.json

Plugin: setu_customization

---

website/static/plugins.json

Plugin: 求生之路2——服务器操作

---

website/static/plugins.json

Plugin: 群聊学习

---

website/static/plugins.json

Plugin: 对对联

---

website/static/plugins.json

Plugin: 云签到

---

website/static/plugins.json

Plugin: 查找图片出处

---

website/static/plugins.json

Plugin: Hypixel数据查询

---

website/static/plugins.json

Plugin: 整点报时

---

website/static/plugins.json

Plugin: 回声洞

---

website/static/plugins.json

Plugin: 星座运势

---

poetry.lock
pyproject.toml

Fix: 屏蔽 fastapi 0.89.0

---

website/static/plugins.json

Plugin: Bing每日图片获取

---

website/static/plugins.json

Plugin: 心灵鸡汤

---

website/static/bots.json

Bot: 辞辞(cici)Bot

---

website/static/plugins.json

不出意外应该是最后一次大更新了，10个小游戏的目标已经完成
Plugins：删除插件ayaka
只有一个人用且无法直接实现功能的插件放在商店里不合时宜

Plugins: 更新 ayaka_games 插件名和描述

---

website/static/plugins.json

Plugin: 原神实时公告

---

website/static/plugins.json

nonebot-plugin-javamc-status 改为 nonebot-plugin-mc_server-status

Plugin: 更新 MC 的插件信息

---

website/static/plugins.json

Plugin: 哔哩哔哩q群登录

---

website/static/plugins.json

Plugin: 简易谷歌翻译插件

---

website/static/plugins.json

Plugin: OrangeDice!

---

website/static/plugins.json

Plugin: 语音功能

---

website/static/plugins.json

Plugin: 喵喵自记菜谱

---

website/static/bots.json

Bot: SuzunoBot

---

website/static/plugins.json

Plugin: 犯人在跳舞

---

website/static/adapters.json

Adapter: Spigot

---

website/static/plugins.json

Plugin: PicMCStat

---

website/static/plugins.json

Plugin: 反向词典

---

website/static/adapters.json

Adapter: BilibiliLive

---

website/static/plugins.json

- [nonebot_plugin_flash_silentsave](https://github.com/KarisAya/nonebot_plugin_flash_silentsave) @KarisAya requests
- [nonebot-plugin-magiadice](https://github.com/sena-nana/nonebot-plugin-magiadice) @sena-nana wcwidth
- [nonebot-plugin-myb-exchange](https://github.com/CMHopeSunshine/LittlePaimon/tree/Bot/src/plugins/nonebot_plugin_myb_exchange) @CMHopeSunshine
- [nonebot2-plugin-eth-terminal](https://github.com/Sclock/nonebot2_plugin_eth_terminal) @Sclock httpx
- [nonebot-plugin-vf](https://github.com/snowyfirefly/VirtualFriends) @snowyfirefly 上次忘删
- [nonebot-plugin-auto-teenstudy](https://github.com/ZMXC01/nonebot_plugin_auto_teenstudy) @ZMXC01 requests
- [nonebot-plugin-ykt](https://github.com/sena-nana/nonebot-plugin-ykt) @sena-nana nonebot-plugin-apscheduler
- …

Docs: 移除商店中的过期插件 2023

---

website/static/plugins.json

Plugin: 植物大战僵尸小游戏

---

website/static/plugins.json

Plugin: 摩尔质量计算器

---

website/static/plugins.json

Plugin: 对话超管

---

website/static/plugins.json

Plugin: 青岚

---

website/static/plugins.json

Plugin: 简易群管女生自用99新

---

website/static/plugins.json

Plugin: Group_Link_Guild

---

website/static/plugins.json

Plugin: Alconna 命令工具

---

website/static/plugins.json

Plugin: nonebot-plugin-mcport

---

website/static/plugins.json

Plugin: XDU校园服务

---

website/static/plugins.json

Plugin: 查找轻小说

---

website/static/plugins.json

Plugin: 舔狗日记

---

website/static/plugins.json

Plugin: uuid生成器

---

website/static/plugins.json

Plugin: impact淫趴

---

website/static/plugins.json

Plugin: MC Ping

---

website/static/plugins.json

Plugin: 我要一张xx涩图

---

website/static/plugins.json

Plugin: 每日人品2

---

website/static/plugins.json

Plugin: DickyPK

---

website/static/plugins.json

Plugin: Q群消息事件监控

---

website/static/bots.json

Bot: ChensQBOTv2

---

website/static/adapters.json

Fix: 修改 bilibili live 的模块路径

---

website/static/plugins.json

Plugin: 今天吃喝什么（图片版）

---

website/static/bots.json

Bot: koishi

---

website/static/plugins.json

Plugin: 通用指令阻断

---

website/static/plugins.json

Plugin: ACMReminder

---

website/static/plugins.json

Plugin: 舞萌maimai插件版

---

website/static/plugins.json

Plugin: OneBot 实现

---

website/static/plugins.json

Plugin: 工具拓展

---

website/static/plugins.json

Plugin: 原神深境螺旋数据查询

---

website/static/plugins.json

Plugin: 你画我猜组队

---

website/static/plugins.json

Plugin: 视频、图片解析器

---

website/static/plugins.json

Plugin: Bing Chat

---

website/static/plugins.json

更新插件（https://github.com/zhiyu1998/nonebot-plugin-resolver）名称，更接地气更接近功能名～

Plugin: 修改链接分享解析器插件名称

---

nonebot/plugin/manager.py

Feature: 优化插件加载日志

---

nonebot/plugin/load.py
poetry.lock
pyproject.toml

Feature: 使用 `tomllib` 读取 toml 配置

---

website/versioned_docs/version-2.0.0rc3/start/install-adapter.mdx
website/versioned_docs/version-2.0.0rc3/start/install-driver.mdx
website/versioned_docs/version-2.0.0rc3/start/install-plugin.mdx

Docs: 修正交互模式命令

---

website/static/plugins.json

Plugin: 峯驰物流

---

website/static/plugins.json

Plugin: 发病语录

---

website/static/plugins.json

Plugin: 修仙_2.0

---

website/static/plugins.json

Plugin: 呆呆兽都会起来锻炼 H2E

---

website/static/plugins.json

Plugin: 呆呆兽都会用的chatbot接api

---

website/static/plugins.json

Plugin: wf的wm市场

---

website/static/plugins.json

Plugin: 战地一入群审批

---

website/static/plugins.json

Plugin: 爱发电审核

---

website/static/plugins.json

Plugin: nonebot_plugin_eventdone

---

website/static/plugins.json

Plugin: 青年大学习提交(Web UI)

---

website/static/plugins.json

Plugin: 60s日历

---

website/static/plugins.json

Plugin: AutoRepeater

---

website/static/plugins.json

Plugin: 小爱课程表

---

website/static/plugins.json

Plugin: Sanae

---

website/static/bots.json

Bot: LOVE酱

---

website/static/bots.json

Bot: fubot

---

website/static/plugins.json

Plugin: 明日方舟抽卡记录分析

---

website/static/plugins.json

Plugin: ChatGPT官方接口版

---

website/static/plugins.json

Plugin: 多功能的ChatGPT机器人

---

website/static/plugins.json

Plugin: 和团子聊天！

---

website/static/plugins.json

Plugin: ChatPDF文章分析

---

website/static/plugins.json

Plugin: RimoFun

---

website/static/plugins.json

Plugin: 群聊自定义表情包

---

website/static/plugins.json

Plugin: 发6

---

website/static/plugins.json

Plugin: 括号补全

---

website/static/plugins.json

Plugin: 原神历史卡池

---

website/static/plugins.json

Plugin: unoconv文件转换

---

website/static/plugins.json

Plugin: apex信息查询

---

website/static/plugins.json

Plugin: 随机狗妈

---

website/static/plugins.json

Plugin: 群聊语录库

---

website/static/plugins.json

Plugin: 表情包制作（调用API版）

---

website/static/plugins.json

Plugin: 随机点名

---

website/static/plugins.json

Plugin: 多平台热搜获取插件

---

website/static/plugins.json

Plugin: ChatGLM

---

website/static/plugins.json

Plugin: ChatGLM-6B API版

---

nonebot/consts.py
nonebot/drivers/none.py

配合 <https://github.com/nonebot/nb-cli/pull/71>，修复在 Windows 上无法重载的问题。

Feature: 在 Windows 上处理 SIGBREAK 信号

---

website/static/plugins.json

Plugin: 喵喵点歌

---

website/static/plugins.json

Plugin: Hello World

---

website/static/plugins.json

Plugin: 通括膨胀

---

website/static/plugins.json

Plugin: nonebot-plugin-miao

---

website/static/plugins.json

Plugin: 颠倒问号

---

website/docs/tutorial/message.md

Docs: 添加 Message 基类模板使用警告

---

website/static/plugins.json

Plugin: 原神cos

---

nonebot/plugin/on.py

Fix: 修复事件响应器辅助函数丢失 block

---

website/static/plugins.json

Plugin: ChatGPT网页端API

---

website/static/plugins.json

Plugin: ROLL

---

website/static/plugins.json

Plugin: 激战2！！！

---

website/static/plugins.json

Plugin: 今日老婆

---

website/static/plugins.json

Plugin: 来份睡眠套餐

---

website/static/adapters.json

Adapter: Walle-Q

---

website/docs/best-practice/deployment.mdx

Docs: 更新部署文档

---

website/static/plugins.json

Plugin: nonebot_api_paddle

---

website/static/plugins.json

Plugin: AI生成PPT

---

website/static/plugins.json

Plugin: Steam游戏状态播报

---

.github/workflows/publish-bot.yml
.github/workflows/release-drafter.yml
.github/workflows/release.yml

CI: 使用 NoneFlow 管理工作流

---

.github/workflows/noneflow.yml

CI: 跳过 PR 仓库为 fork 的情况

---

README.md
website/static/adapters.json

nonebot-adapter-spigot能力提升，改名为nonebot-adapter-minecraft

Adapter: 更新 Minecraft 适配器

---

nonebot/rule.py
tests/test_rule.py

Fix: 修复命令强制空白符影响无参数情况

---

website/versioned_docs/version-2.0.0rc4/tutorial/event-data.mdx

Docs: 修复获取事件信息文档代码范例中缺失的 import

---

.github/ISSUE_TEMPLATE/adapter_publish.yml
.github/ISSUE_TEMPLATE/bot_publish.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/plugin_publish.yml
website/src/components/Adapter.tsx
website/src/components/Bot.tsx
website/src/components/Plugin.tsx

@nonebot/noneflow NoneFlow需要进行对应的匹配修改

Docs: 使用 issue form 进行商店发布

---

website/static/plugins.json

Plugin: 移除 extrautils 工具拓展插件（暂停维护）

---

nonebot/internal/params.py
nonebot/utils.py
tests/plugins/param/priority.py
tests/test_param.py

Feature: 移除部分依赖注入参数默认值检查

---

website/static/bots.json
website/static/plugins.json

长时间未更新
移除
- nonebot-plugin-atri
- gocqapi
- Takker

Plugin: 移除过时未更新的插件&Bot

---

.github/workflows/noneflow.yml

CI: 缓存 NoneFlow 所需的 pre-commit hooks

---

website/docs/appendices/log.md

Related to https://github.com/orgs/nonebot/discussions/391

Docs: 修复日志自定义文档 typo

---

website/static/plugins.json

Plugin: 更新 SparkGPT 插件描述

---

nonebot/drivers/quart.py
tests/test_broadcast.py
tests/test_driver.py

https://github.com/pallets/quart/blob/main/src/quart/ctx.py#L376
fix #2097

Fix: 修复 Quart WS task 上下文错误

---

.gitattributes
pyproject.toml

check file attributes with:
```bash
git check-attr -a -- <file-name>
```

Develop: 添加 git attributes 定义

---

.github/workflows/website-deploy.yml
.github/workflows/website-preview.yml

[facebook/docusaurus/issues/2798](https://github.com/facebook/docusaurus/issues/2798)

Docs: 修复文档 Last updated author 错误

---

website/docs/developer/adapter-writing.md
website/src/pages/changelog.md

Docs: 适配器编写教程

---

.github/workflows/noneflow.yml

CI: 插件测试使用最新的稳定版 Python 版本

---

website/static/plugins.json

🗑️ Remove Plugin nonebot_plugin_heisi
ℹ️ 下架原因：不再维护

Plugin: 删除插件 nonebot-plugin-heisi

---

website/docusaurus.config.js
website/src/theme/FooterCopyright/index.tsx
website/src/theme/TOC/index.tsx
website/src/theme/TOC/styles.module.css

Docs: 添加 wwads

---

.github/dependabot.yml
.github/workflows/release-drafter.yml

- release drafter 使用 noneflow 的 token
- 使用 trusted publisher
- 设置 dependabot groups

CI: 使用更现代的功能

---

assets/plugins.json

[C U AGAIN](https://www.bilibili.com/video/BV1vV41137cB)

Plugin: 移除不再维护的插件

---

assets/plugins.json

This reverts commit aecff5ffd6b80daee4866845c0c7c0bc41b4e6c3.

Plugin: 恢复删除的插件 `nonebot-plugin-eitherchoice`

---

nonebot/drivers/websockets.py
poetry.lock
pyproject.toml
tests/fake_server.py
tests/test_driver.py

Fix: websockets 驱动器连接关闭 code 获取错误

---

.devcontainer/devcontainer.json
.prettierrc
tsconfig.json

see prettier/prettier#15942 prettier/prettier#15956

CI: 更新 prettier 配置

---

assets/plugins.json

Plugin: 移除不维护的插件 `eitherchoice`

---

README.md

Docs: 添加 RocketChat 适配器说明

---

envs/pydantic-v1/poetry.lock
envs/pydantic-v2/poetry.lock
envs/test/poetry.lock
nonebot/typing.py
poetry.lock

参考 <https://github.com/pydantic/pydantic/pull/9612> 进行修复。

Fix: 修复 ForwardRef eval 时参数 recursive_guard 缺失

---

assets/plugins.json

Plugin: 修改插件 miragetank & charpic 信息

---

assets/plugins.json

Plugin: 更新插件 sparkapi 信息

---

assets/plugins.json

Plugin: 移除 kanonbot 插件

---

assets/plugins.json

Plugin: 修改插件 system-command 信息

---

assets/plugins.json

Plugin: 删除`function` 插件，添加 `batch-withdrawal` 插件标签

---

.github/workflows/noneflow.yml
assets/adapters.json5
assets/bots.json5
assets/drivers.json5
assets/plugins.json5

大幅简化 Workflow，将插件测试移动至 NoneFlow 中，同时修改 assets 格式为 json5 ~~（本来想减少冲突的概率但不太可靠）~~。

CI: 使用最新版的 NoneFlow

---

README.md

Docs: 添加 Mail 适配器说明

---

README.md

Docs: 添加 微信公众平台 适配器描述

---

.github/workflows/release-drafter.yml

https://github.com/release-drafter/release-drafter/issues/1424
由于 change template 输出的 changelog 不对劲

CI: 临时降级 release-drafter

---

README.md

Docs: 添加 Gewechat 适配器描述

---

assets/plugins.json5

Plugin: 修改 nailong 插件作者

---

.github/workflows/codecov.yml
tests/test_param.py

https://github.com/python/cpython/issues/137317

CI: 测试矩阵加入 Python 3.13

---

assets/plugins.json5
website/docs/best-practice/htmlkit-render.md
website/versioned_docs/version-2.4.1/best-practice/htmlkit-render.md
website/versioned_docs/version-2.4.2/best-practice/htmlkit-render.md
website/versioned_docs/version-2.4.3/best-practice/htmlkit-render.md

> OSPP 2025 NoneBot HTML 渲染插件的一部分

Docs: 添加 htmlkit 文档至最佳实践
